import type { TemplateDefinition } from "../types.js";

export const DAILY_SALES_REPORT: TemplateDefinition = {
  id: "daily-sales-report",
  name: "Daily Sales Report",
  category: "sales",
  description:
    "Track daily item sales with unit prices, quantities, tax calculations, and line totals with alternating row shading.",
  design: {
    palette: {
      titleBg: "#11545B",
      titleFg: "#FFFFFF",
      headerBg: "#D9F9FF",
      headerFg: "#000000",
      labelBg: "#D9F9FF",
      labelFg: "#000000",
      accentBg: "#DD7CF8",
      accentFg: "#000000",
      alternateBg: "#E8E8E8",
      totalBg: "#D9F9FF",
      totalFg: "#000000",
    },
    typography: {
      fontFamily: "Franklin Gothic Book",
      titleFontFamily: "Franklin Gothic Book",
      titleSize: 52,
      sectionHeaderSize: 14,
      headerSize: 14,
      bodySize: 11,
    },
    alternatingRows: true,
    titleBold: true,
    titleRowHeight: 66,
    defaultRowHeight: 20,
    headerRowHeight: 28,
  },
  structure: {
    title: "Daily Sales Report",
    titleRow: 1,
    metaFields: [
      { label: "Business Name:", placeholder: "Acme Corp", row: 2, labelCol: "A", valueCol: "B" },
      { label: "Date:", placeholder: "03/15/2026", row: 2, labelCol: "E", valueCol: "F" },
      { label: "Salesperson:", placeholder: "Jane Doe", row: 3, labelCol: "A", valueCol: "B" },
      { label: "Register No.:", placeholder: "R-001", row: 3, labelCol: "E", valueCol: "F" },
    ],
    headerRow: 4,
    columns: [
      { header: "Item No.", col: "A", width: 10, alignment: "Center" },
      { header: "Item Name", col: "B", width: 18, alignment: "Left" },
      { header: "Description", col: "C", width: 22, alignment: "Left" },
      { header: "Unit Price", col: "D", width: 12, alignment: "Right" },
      { header: "Qty", col: "E", width: 8, alignment: "Center" },
      { header: "Subtotal", col: "F", width: 14, alignment: "Right" },
      { header: "Tax Rate", col: "G", width: 10, alignment: "Center" },
      { header: "Tax Amt", col: "H", width: 12, alignment: "Right" },
      { header: "Total", col: "I", width: 14, alignment: "Right", isAccent: true },
    ],
    sampleData: [
      [1, "Widget A", "Standard widget", 25.00, 10, 250.00, "8%", 20.00, 270.00],
      [2, "Widget B", "Premium widget", 45.00, 5, 225.00, "8%", 18.00, 243.00],
      [3, "Gadget C", "Compact gadget", 15.50, 20, 310.00, "8%", 24.80, 334.80],
      [4, "Gadget D", "Deluxe gadget", 62.00, 3, 186.00, "8%", 14.88, 200.88],
      [5, "Part E", "Replacement part", 8.75, 50, 437.50, "5%", 21.88, 459.38],
      [6, "Part F", "Accessory pack", 12.00, 4, 48.00, "5%", 2.40, 50.40],
      [7, "Service G", "Installation", 0.00, 1, 0.00, "0%", 0.00, 0.00],
    ],
    totalRow: {
      row: 12,
      label: "TOTAL",
      labelCol: "A",
      values: { F: 1456.50, H: 101.96, I: 1558.46 },
    },
    zones: [
      { type: "title", rows: 1 },
      { type: "meta", rows: [2, 3] },
      { type: "column_header", rows: 4 },
      { type: "data", rows: 5 },
      { type: "data_alternate", rows: 6 },
      { type: "data", rows: 7 },
      { type: "data_alternate", rows: 8 },
      { type: "data", rows: 9 },
      { type: "data_alternate", rows: 10 },
      { type: "data", rows: 11 },
      { type: "total", rows: 12 },
    ],
    columnSpan: "A:I",
    totalRows: 12,
  },
  sourceKind: "bundled",
};
