import type { TemplateDefinition } from "../types.js";

export const EMPLOYEE_SCHEDULE: TemplateDefinition = {
  id: "employee-schedule",
  name: "Employee Schedule Sheet",
  category: "schedule",
  description:
    "Plan weekly employee shifts with role assignments, hours tracking, and schedule overview.",
  design: {
    palette: {
      titleBg: "#305496",
      titleFg: "#FFFFFF",
      headerBg: "#D6E4F0",
      headerFg: "#000000",
      labelBg: "#D6E4F0",
      labelFg: "#000000",
      accentBg: "#305496",
      accentFg: "#FFFFFF",
      alternateBg: "#F2F2F2",
      totalBg: "#D6E4F0",
      totalFg: "#000000",
    },
    typography: {
      fontFamily: "Calibri",
      titleFontFamily: "Calibri",
      titleSize: 26,
      sectionHeaderSize: 14,
      headerSize: 11,
      bodySize: 11,
    },
    alternatingRows: true,
    titleBold: true,
    titleRowHeight: 40,
    defaultRowHeight: 20,
    headerRowHeight: 25,
  },
  structure: {
    title: "Employee Schedule Sheet",
    titleRow: 1,
    metaFields: [
      { label: "Department:", placeholder: "Operations", row: 2, labelCol: "A", valueCol: "B" },
      { label: "Week Of:", placeholder: "03/16/2026", row: 2, labelCol: "F", valueCol: "G" },
      { label: "Manager:", placeholder: "Jane Doe", row: 3, labelCol: "A", valueCol: "B" },
      { label: "Location:", placeholder: "Main Office", row: 3, labelCol: "F", valueCol: "G" },
    ],
    headerRow: 5,
    columns: [
      { header: "Employee", col: "A", width: 18, alignment: "Left" },
      { header: "Role", col: "B", width: 14, alignment: "Left" },
      { header: "Monday", col: "C", width: 12, alignment: "Center" },
      { header: "Tuesday", col: "D", width: 12, alignment: "Center" },
      { header: "Wednesday", col: "E", width: 12, alignment: "Center" },
      { header: "Thursday", col: "F", width: 12, alignment: "Center" },
      { header: "Friday", col: "G", width: 12, alignment: "Center" },
      { header: "Saturday", col: "H", width: 12, alignment: "Center" },
      { header: "Sunday", col: "I", width: 12, alignment: "Center" },
      { header: "Total Hrs", col: "J", width: 10, alignment: "Right", isAccent: true },
    ],
    sampleData: [
      ["Alice Johnson", "Manager", "9A-5P", "9A-5P", "9A-5P", "9A-5P", "9A-5P", "OFF", "OFF", 40],
      ["Bob Smith", "Supervisor", "8A-4P", "8A-4P", "8A-4P", "8A-4P", "8A-4P", "OFF", "OFF", 40],
      ["Carol White", "Associate", "10A-6P", "10A-6P", "OFF", "10A-6P", "10A-6P", "10A-4P", "OFF", 38],
      ["Dave Brown", "Associate", "OFF", "12P-8P", "12P-8P", "12P-8P", "12P-8P", "12P-8P", "OFF", 40],
      ["Eve Davis", "Part-Time", "9A-1P", "9A-1P", "9A-1P", "OFF", "OFF", "9A-1P", "9A-1P", 20],
      ["Frank Lee", "Associate", "8A-4P", "OFF", "8A-4P", "8A-4P", "OFF", "8A-4P", "8A-4P", 40],
    ],
    totalRow: {
      row: 12,
      label: "TOTAL HOURS",
      labelCol: "A",
      values: { J: 218 },
    },
    zones: [
      { type: "title", rows: 1 },
      { type: "meta", rows: [2, 3] },
      { type: "spacer", rows: 4 },
      { type: "column_header", rows: 5 },
      { type: "data", rows: 6 },
      { type: "data_alternate", rows: 7 },
      { type: "data", rows: 8 },
      { type: "data_alternate", rows: 9 },
      { type: "data", rows: 10 },
      { type: "data_alternate", rows: 11 },
      { type: "total", rows: 12 },
    ],
    columnSpan: "A:J",
    totalRows: 12,
  },
  sourceKind: "bundled",
};
