import type { TemplateDefinition } from "../types.js";

export const GOAL_TRACKING: TemplateDefinition = {
  id: "goal-tracking",
  name: "Goal Tracking Sheet",
  category: "tracking",
  description:
    "Track personal or team goals across categories like health, career, finance, and education with progress indicators.",
  design: {
    palette: {
      titleBg: "#385723",
      titleFg: "#FFFFFF",
      headerBg: "#E2EFDA",
      headerFg: "#000000",
      labelBg: "#E2EFDA",
      labelFg: "#000000",
      accentBg: "#385723",
      accentFg: "#FFFFFF",
      alternateBg: "#F2F2F2",
      totalBg: "#E2EFDA",
      totalFg: "#000000",
    },
    typography: {
      fontFamily: "Calibri",
      titleFontFamily: "Calibri",
      titleSize: 26,
      sectionHeaderSize: 14,
      headerSize: 11,
      bodySize: 11,
    },
    alternatingRows: false,
    titleBold: true,
    titleRowHeight: 40,
    defaultRowHeight: 20,
    headerRowHeight: 25,
  },
  structure: {
    title: "Goal Tracking Sheet",
    titleRow: 1,
    metaFields: [
      { label: "Name:", placeholder: "John Smith", row: 2, labelCol: "A", valueCol: "B" },
      { label: "Year:", placeholder: "2026", row: 2, labelCol: "E", valueCol: "F" },
      { label: "Review Cycle:", placeholder: "Quarterly", row: 3, labelCol: "A", valueCol: "B" },
      { label: "Last Updated:", placeholder: "03/15/2026", row: 3, labelCol: "E", valueCol: "F" },
    ],
    headerRow: 5,
    columns: [
      { header: "Goal #", col: "A", width: 8, alignment: "Center" },
      { header: "Goal Description", col: "B", width: 28, alignment: "Left" },
      { header: "Key Result / Metric", col: "C", width: 22, alignment: "Left" },
      { header: "Target", col: "D", width: 14, alignment: "Center" },
      { header: "Current", col: "E", width: 14, alignment: "Center" },
      { header: "Progress", col: "F", width: 12, alignment: "Center", isAccent: true },
      { header: "Status", col: "G", width: 14, alignment: "Center", isAccent: true },
      { header: "Deadline", col: "H", width: 12, alignment: "Center" },
      { header: "Notes", col: "I", width: 20, alignment: "Left" },
    ],
    sampleData: [
      [1, "Run a half marathon", "Weekly miles logged", "20 mi/wk", "14 mi/wk", "70%", "On Track", "09/30/2026", "Training plan active"],
      [2, "Lose 15 lbs", "Weight (lbs)", "170", "178", "53%", "Behind", "06/30/2026", "Diet adjustments needed"],
      [3, "Get promoted to Sr. Engineer", "Performance review score", "Exceeds", "Meets", "50%", "On Track", "12/31/2026", "Mentor sessions booked"],
      [4, "Complete AWS certification", "Exam passed", "Pass", "Studying", "40%", "On Track", "06/30/2026", "Practice exams started"],
      [5, "Save $10,000 emergency fund", "Savings balance", "$10,000", "$6,500", "65%", "On Track", "12/31/2026", "$500/mo auto-transfer"],
      [6, "Pay off credit card debt", "Outstanding balance", "$0", "$2,100", "58%", "On Track", "09/30/2026", "Extra payments monthly"],
    ],
    zones: [
      { type: "title", rows: 1 },
      { type: "meta", rows: [2, 3] },
      { type: "spacer", rows: 4 },
      { type: "section_header", rows: 5 },
      { type: "column_header", rows: 6 },
      { type: "data", rows: 7 },
      { type: "data", rows: 8 },
      { type: "spacer", rows: 9 },
      { type: "section_header", rows: 10 },
      { type: "column_header", rows: 11 },
      { type: "data", rows: 12 },
      { type: "data", rows: 13 },
      { type: "spacer", rows: 14 },
      { type: "section_header", rows: 15 },
      { type: "column_header", rows: 16 },
      { type: "data", rows: 17 },
      { type: "data", rows: 18 },
      { type: "spacer", rows: 19 },
      { type: "section_header", rows: 20 },
      { type: "column_header", rows: 21 },
      { type: "data", rows: 22 },
      { type: "data", rows: 23 },
    ],
    sections: [
      {
        name: "Health & Fitness",
        headerRow: 5,
        headerRow2: 6,
        columns: [
          { header: "Goal #", col: "A", width: 8, alignment: "Center" },
          { header: "Goal Description", col: "B", width: 28, alignment: "Left" },
          { header: "Key Result / Metric", col: "C", width: 22, alignment: "Left" },
          { header: "Target", col: "D", width: 14, alignment: "Center" },
          { header: "Current", col: "E", width: 14, alignment: "Center" },
          { header: "Progress", col: "F", width: 12, alignment: "Center", isAccent: true },
          { header: "Status", col: "G", width: 14, alignment: "Center", isAccent: true },
          { header: "Deadline", col: "H", width: 12, alignment: "Center" },
          { header: "Notes", col: "I", width: 20, alignment: "Left" },
        ],
        sampleData: [
          [1, "Run a half marathon", "Weekly miles logged", "20 mi/wk", "14 mi/wk", "70%", "On Track", "09/30/2026", "Training plan active"],
          [2, "Lose 15 lbs", "Weight (lbs)", "170", "178", "53%", "Behind", "06/30/2026", "Diet adjustments needed"],
        ],
      },
      {
        name: "Career & Professional",
        headerRow: 10,
        headerRow2: 11,
        columns: [
          { header: "Goal #", col: "A", width: 8, alignment: "Center" },
          { header: "Goal Description", col: "B", width: 28, alignment: "Left" },
          { header: "Key Result / Metric", col: "C", width: 22, alignment: "Left" },
          { header: "Target", col: "D", width: 14, alignment: "Center" },
          { header: "Current", col: "E", width: 14, alignment: "Center" },
          { header: "Progress", col: "F", width: 12, alignment: "Center", isAccent: true },
          { header: "Status", col: "G", width: 14, alignment: "Center", isAccent: true },
          { header: "Deadline", col: "H", width: 12, alignment: "Center" },
          { header: "Notes", col: "I", width: 20, alignment: "Left" },
        ],
        sampleData: [
          [3, "Get promoted to Sr. Engineer", "Performance review score", "Exceeds", "Meets", "50%", "On Track", "12/31/2026", "Mentor sessions booked"],
          [4, "Complete AWS certification", "Exam passed", "Pass", "Studying", "40%", "On Track", "06/30/2026", "Practice exams started"],
        ],
      },
      {
        name: "Finance",
        headerRow: 15,
        headerRow2: 16,
        columns: [
          { header: "Goal #", col: "A", width: 8, alignment: "Center" },
          { header: "Goal Description", col: "B", width: 28, alignment: "Left" },
          { header: "Key Result / Metric", col: "C", width: 22, alignment: "Left" },
          { header: "Target", col: "D", width: 14, alignment: "Center" },
          { header: "Current", col: "E", width: 14, alignment: "Center" },
          { header: "Progress", col: "F", width: 12, alignment: "Center", isAccent: true },
          { header: "Status", col: "G", width: 14, alignment: "Center", isAccent: true },
          { header: "Deadline", col: "H", width: 12, alignment: "Center" },
          { header: "Notes", col: "I", width: 20, alignment: "Left" },
        ],
        sampleData: [
          [5, "Save $10,000 emergency fund", "Savings balance", "$10,000", "$6,500", "65%", "On Track", "12/31/2026", "$500/mo auto-transfer"],
          [6, "Pay off credit card debt", "Outstanding balance", "$0", "$2,100", "58%", "On Track", "09/30/2026", "Extra payments monthly"],
        ],
      },
      {
        name: "Education & Learning",
        headerRow: 20,
        headerRow2: 21,
        columns: [
          { header: "Goal #", col: "A", width: 8, alignment: "Center" },
          { header: "Goal Description", col: "B", width: 28, alignment: "Left" },
          { header: "Key Result / Metric", col: "C", width: 22, alignment: "Left" },
          { header: "Target", col: "D", width: 14, alignment: "Center" },
          { header: "Current", col: "E", width: 14, alignment: "Center" },
          { header: "Progress", col: "F", width: 12, alignment: "Center", isAccent: true },
          { header: "Status", col: "G", width: 14, alignment: "Center", isAccent: true },
          { header: "Deadline", col: "H", width: 12, alignment: "Center" },
          { header: "Notes", col: "I", width: 20, alignment: "Left" },
        ],
        sampleData: [
          [7, "Read 24 books this year", "Books completed", "24", "7", "29%", "On Track", "12/31/2026", "2 books/month pace"],
          [8, "Learn Spanish (B1 level)", "Duolingo streak & exam", "B1 Cert", "A2", "50%", "On Track", "12/31/2026", "Daily 30 min practice"],
        ],
      },
    ],
    columnSpan: "A:I",
    totalRows: 23,
  },
  sourceKind: "bundled",
};
