import type { TemplateDefinition } from "../types.js";

export const MEETING_ATTENDANCE: TemplateDefinition = {
  id: "meeting-attendance",
  name: "Meeting Attendance Sheet",
  category: "schedule",
  description:
    "Track meeting attendance with participant details, check-in times, and notes.",
  design: {
    palette: {
      titleBg: "#4472C4",
      titleFg: "#FFFFFF",
      headerBg: "#D6E4F0",
      headerFg: "#000000",
      labelBg: "#D6E4F0",
      labelFg: "#000000",
      accentBg: "#4472C4",
      accentFg: "#FFFFFF",
      alternateBg: "#F2F2F2",
      totalBg: "#D6E4F0",
      totalFg: "#000000",
    },
    typography: {
      fontFamily: "Calibri",
      titleFontFamily: "Calibri",
      titleSize: 26,
      sectionHeaderSize: 14,
      headerSize: 11,
      bodySize: 11,
    },
    alternatingRows: true,
    titleBold: true,
    titleRowHeight: 40,
    defaultRowHeight: 20,
    headerRowHeight: 25,
  },
  structure: {
    title: "Meeting Attendance Sheet",
    titleRow: 1,
    metaFields: [
      { label: "Meeting Title:", placeholder: "Weekly Standup", row: 2, labelCol: "A", valueCol: "B" },
      { label: "Date:", placeholder: "03/15/2026", row: 2, labelCol: "D", valueCol: "E" },
      { label: "Location:", placeholder: "Conference Room A", row: 3, labelCol: "A", valueCol: "B" },
      { label: "Organizer:", placeholder: "Jane Doe", row: 3, labelCol: "D", valueCol: "E" },
    ],
    headerRow: 5,
    columns: [
      { header: "No.", col: "A", width: 6, alignment: "Center" },
      { header: "Full Name", col: "B", width: 20, alignment: "Left" },
      { header: "Department", col: "C", width: 16, alignment: "Left" },
      { header: "Email", col: "D", width: 24, alignment: "Left" },
      { header: "Check-In Time", col: "E", width: 14, alignment: "Center" },
      { header: "Signature", col: "F", width: 16, alignment: "Center" },
      { header: "Notes", col: "G", width: 22, alignment: "Left" },
    ],
    sampleData: [
      [1, "Alice Johnson", "Engineering", "alice@example.com", "9:00 AM", "", "On time"],
      [2, "Bob Smith", "Marketing", "bob@example.com", "9:05 AM", "", "Late 5 min"],
      [3, "Carol White", "Design", "carol@example.com", "8:58 AM", "", ""],
      [4, "Dave Brown", "Sales", "dave@example.com", "9:02 AM", "", ""],
      [5, "Eve Davis", "HR", "eve@example.com", "9:00 AM", "", "Remote"],
    ],
    zones: [
      { type: "title", rows: 1 },
      { type: "meta", rows: [2, 3] },
      { type: "spacer", rows: 4 },
      { type: "column_header", rows: 5 },
      { type: "data", rows: 6 },
      { type: "data_alternate", rows: 7 },
      { type: "data", rows: 8 },
      { type: "data_alternate", rows: 9 },
      { type: "data", rows: 10 },
    ],
    columnSpan: "A:G",
    totalRows: 10,
  },
  sourceKind: "bundled",
};
