import type { TemplateDefinition } from "../types.js";

export const MONTHLY_TIME_SHEET: TemplateDefinition = {
  id: "monthly-time-sheet",
  name: "Monthly Time Sheet",
  category: "schedule",
  description:
    "Record daily work hours for an entire month with overtime calculations and approval fields.",
  design: {
    palette: {
      titleBg: "#305496",
      titleFg: "#FFFFFF",
      headerBg: "#D6E4F0",
      headerFg: "#000000",
      labelBg: "#D6E4F0",
      labelFg: "#000000",
      accentBg: "#305496",
      accentFg: "#FFFFFF",
      alternateBg: "#F2F2F2",
      totalBg: "#D6E4F0",
      totalFg: "#000000",
    },
    typography: {
      fontFamily: "Calibri",
      titleFontFamily: "Calibri",
      titleSize: 26,
      sectionHeaderSize: 14,
      headerSize: 11,
      bodySize: 11,
    },
    alternatingRows: true,
    titleBold: true,
    titleRowHeight: 40,
    defaultRowHeight: 20,
    headerRowHeight: 25,
  },
  structure: {
    title: "Monthly Time Sheet",
    titleRow: 1,
    metaFields: [
      { label: "Employee Name:", placeholder: "John Smith", row: 2, labelCol: "A", valueCol: "B" },
      { label: "Month:", placeholder: "March 2026", row: 2, labelCol: "D", valueCol: "E" },
      { label: "Department:", placeholder: "Engineering", row: 3, labelCol: "A", valueCol: "B" },
      { label: "Manager:", placeholder: "Jane Doe", row: 3, labelCol: "D", valueCol: "E" },
    ],
    headerRow: 5,
    columns: [
      { header: "Date", col: "A", width: 12, alignment: "Center" },
      { header: "Day", col: "B", width: 10, alignment: "Center" },
      { header: "Start Time", col: "C", width: 12, alignment: "Center" },
      { header: "End Time", col: "D", width: 12, alignment: "Center" },
      { header: "Break (hrs)", col: "E", width: 12, alignment: "Center" },
      { header: "Regular Hrs", col: "F", width: 12, alignment: "Right" },
      { header: "Overtime Hrs", col: "G", width: 12, alignment: "Right" },
      { header: "Total Hrs", col: "H", width: 12, alignment: "Right", isAccent: true },
    ],
    sampleData: [
      ["03/01", "Mon", "9:00 AM", "5:30 PM", 0.5, 8.0, 0.0, 8.0],
      ["03/02", "Tue", "8:30 AM", "6:00 PM", 0.5, 8.0, 1.0, 9.0],
      ["03/03", "Wed", "9:00 AM", "5:00 PM", 0.5, 7.5, 0.0, 7.5],
      ["03/04", "Thu", "9:00 AM", "5:30 PM", 0.5, 8.0, 0.0, 8.0],
      ["03/05", "Fri", "8:00 AM", "4:30 PM", 0.5, 8.0, 0.0, 8.0],
    ],
    totalRow: {
      row: 38,
      label: "TOTAL",
      labelCol: "A",
      values: { F: 160.0, G: 4.0, H: 164.0 },
    },
    zones: [
      { type: "title", rows: 1 },
      { type: "meta", rows: [2, 3] },
      { type: "spacer", rows: 4 },
      { type: "column_header", rows: 5 },
      { type: "data", rows: 6 },
      { type: "data_alternate", rows: 7 },
      { type: "data", rows: 8 },
      { type: "data_alternate", rows: 9 },
      { type: "data", rows: 10 },
      { type: "total", rows: 38 },
    ],
    columnSpan: "A:H",
    totalRows: 38,
  },
  sourceKind: "bundled",
};
