import type { TemplateDefinition } from "../types.js";

export const RESOURCE_PLANNING: TemplateDefinition = {
  id: "resource-planning",
  name: "Resource Planning Sheet",
  category: "planning",
  description:
    "Allocate team resources across projects with capacity tracking and utilization metrics.",
  design: {
    palette: {
      titleBg: "#4472C4",
      titleFg: "#FFFFFF",
      headerBg: "#D6E4F0",
      headerFg: "#000000",
      labelBg: "#D6E4F0",
      labelFg: "#000000",
      accentBg: "#4472C4",
      accentFg: "#FFFFFF",
      alternateBg: "#F2F2F2",
      totalBg: "#D6E4F0",
      totalFg: "#000000",
    },
    typography: {
      fontFamily: "Calibri",
      titleFontFamily: "Calibri",
      titleSize: 26,
      sectionHeaderSize: 14,
      headerSize: 11,
      bodySize: 11,
    },
    alternatingRows: true,
    titleBold: true,
    titleRowHeight: 40,
    defaultRowHeight: 20,
    headerRowHeight: 25,
  },
  structure: {
    title: "Resource Planning Sheet",
    titleRow: 1,
    metaFields: [
      { label: "Project:", placeholder: "Product Launch v2", row: 2, labelCol: "A", valueCol: "B" },
      { label: "Sprint:", placeholder: "Sprint 12", row: 2, labelCol: "F", valueCol: "G" },
      { label: "Project Manager:", placeholder: "Jane Doe", row: 3, labelCol: "A", valueCol: "B" },
      { label: "Date Range:", placeholder: "03/16 - 03/27/2026", row: 3, labelCol: "F", valueCol: "G" },
    ],
    headerRow: 5,
    columns: [
      { header: "Resource Name", col: "A", width: 18, alignment: "Left" },
      { header: "Role", col: "B", width: 16, alignment: "Left" },
      { header: "Department", col: "C", width: 14, alignment: "Left" },
      { header: "Capacity (hrs)", col: "D", width: 14, alignment: "Right" },
      { header: "Project A (hrs)", col: "E", width: 14, alignment: "Right" },
      { header: "Project B (hrs)", col: "F", width: 14, alignment: "Right" },
      { header: "Project C (hrs)", col: "G", width: 14, alignment: "Right" },
      { header: "Total Allocated", col: "H", width: 14, alignment: "Right", isAccent: true },
      { header: "Available", col: "I", width: 12, alignment: "Right" },
      { header: "Utilization %", col: "J", width: 12, alignment: "Center", isAccent: true },
    ],
    sampleData: [
      ["Alice Johnson", "Developer", "Engineering", 80, 30, 20, 15, 65, 15, "81%"],
      ["Bob Smith", "Designer", "Design", 80, 40, 10, 0, 50, 30, "63%"],
      ["Carol White", "Developer", "Engineering", 80, 20, 30, 25, 75, 5, "94%"],
      ["Dave Brown", "QA Engineer", "Quality", 80, 15, 25, 20, 60, 20, "75%"],
      ["Eve Davis", "PM", "Management", 80, 10, 10, 10, 30, 50, "38%"],
      ["Frank Lee", "Developer", "Engineering", 80, 25, 25, 20, 70, 10, "88%"],
    ],
    totalRow: {
      row: 12,
      label: "TEAM TOTAL",
      labelCol: "A",
      values: { D: 480, E: 140, F: 120, G: 90, H: 350, I: 130 },
    },
    zones: [
      { type: "title", rows: 1 },
      { type: "meta", rows: [2, 3] },
      { type: "spacer", rows: 4 },
      { type: "column_header", rows: 5 },
      { type: "data", rows: 6 },
      { type: "data_alternate", rows: 7 },
      { type: "data", rows: 8 },
      { type: "data_alternate", rows: 9 },
      { type: "data", rows: 10 },
      { type: "data_alternate", rows: 11 },
      { type: "total", rows: 12 },
    ],
    columnSpan: "A:J",
    totalRows: 12,
  },
  sourceKind: "bundled",
};
