import type { TemplateDefinition } from "../types.js";

export const SALES_CONTEST_TRACKER: TemplateDefinition = {
  id: "sales-contest-tracker",
  name: "Sales Contest Tracker",
  category: "sales",
  description:
    "Track sales contest standings with individual rep performance, targets, and ranking.",
  design: {
    palette: {
      titleBg: "#1F4E79",
      titleFg: "#FFFFFF",
      headerBg: "#D6E4F0",
      headerFg: "#000000",
      labelBg: "#D6E4F0",
      labelFg: "#000000",
      accentBg: "#1F4E79",
      accentFg: "#FFFFFF",
      alternateBg: "#F2F2F2",
      totalBg: "#D6E4F0",
      totalFg: "#000000",
    },
    typography: {
      fontFamily: "Calibri",
      titleFontFamily: "Calibri",
      titleSize: 26,
      sectionHeaderSize: 14,
      headerSize: 11,
      bodySize: 11,
    },
    alternatingRows: true,
    titleBold: true,
    titleRowHeight: 40,
    defaultRowHeight: 20,
    headerRowHeight: 25,
  },
  structure: {
    title: "Sales Contest Tracker",
    titleRow: 1,
    metaFields: [
      { label: "Contest Name:", placeholder: "Q1 Sales Blitz", row: 2, labelCol: "A", valueCol: "B" },
      { label: "Start Date:", placeholder: "01/01/2026", row: 2, labelCol: "E", valueCol: "F" },
      { label: "Prize:", placeholder: "$5,000 Bonus", row: 3, labelCol: "A", valueCol: "B" },
      { label: "End Date:", placeholder: "03/31/2026", row: 3, labelCol: "E", valueCol: "F" },
    ],
    headerRow: 5,
    columns: [
      { header: "Rank", col: "A", width: 8, alignment: "Center" },
      { header: "Sales Rep", col: "B", width: 20, alignment: "Left" },
      { header: "Region", col: "C", width: 14, alignment: "Left" },
      { header: "Target", col: "D", width: 14, alignment: "Right" },
      { header: "Actual Sales", col: "E", width: 14, alignment: "Right", isAccent: true },
      { header: "% of Target", col: "F", width: 12, alignment: "Center" },
      { header: "Points", col: "G", width: 10, alignment: "Center", isAccent: true },
    ],
    sampleData: [
      [1, "Sarah Miller", "East", 50000, 62000, "124%", 310],
      [2, "Tom Harris", "West", 50000, 55000, "110%", 275],
      [3, "Liam Chen", "Central", 45000, 48000, "107%", 240],
      [4, "Nina Patel", "South", 45000, 44000, "98%", 195],
      [5, "James Lee", "North", 40000, 38000, "95%", 170],
    ],
    totalRow: {
      row: 11,
      label: "TEAM TOTAL",
      labelCol: "A",
      values: { D: 230000, E: 247000, G: 1190 },
    },
    zones: [
      { type: "title", rows: 1 },
      { type: "meta", rows: [2, 3] },
      { type: "spacer", rows: 4 },
      { type: "column_header", rows: 5 },
      { type: "data", rows: 6 },
      { type: "data_alternate", rows: 7 },
      { type: "data", rows: 8 },
      { type: "data_alternate", rows: 9 },
      { type: "data", rows: 10 },
      { type: "total", rows: 11 },
    ],
    columnSpan: "A:G",
    totalRows: 11,
  },
  sourceKind: "bundled",
};
