import type { TemplateDefinition } from "../types.js";

export const SALES_LEAD_TRACKING: TemplateDefinition = {
  id: "sales-lead-tracking",
  name: "Sales Lead Tracking Sheet",
  category: "sales",
  description:
    "Manage sales leads through the pipeline with contact info, status, value and follow-up dates.",
  design: {
    palette: {
      titleBg: "#2F5496",
      titleFg: "#FFFFFF",
      headerBg: "#D6E4F0",
      headerFg: "#000000",
      labelBg: "#D6E4F0",
      labelFg: "#000000",
      accentBg: "#2F5496",
      accentFg: "#FFFFFF",
      alternateBg: "#F2F2F2",
      totalBg: "#D6E4F0",
      totalFg: "#000000",
    },
    typography: {
      fontFamily: "Calibri",
      titleFontFamily: "Calibri",
      titleSize: 26,
      sectionHeaderSize: 14,
      headerSize: 11,
      bodySize: 11,
    },
    alternatingRows: true,
    titleBold: true,
    titleRowHeight: 40,
    defaultRowHeight: 20,
    headerRowHeight: 25,
  },
  structure: {
    title: "Sales Lead Tracking Sheet",
    titleRow: 1,
    metaFields: [
      { label: "Sales Rep:", placeholder: "Jane Doe", row: 2, labelCol: "A", valueCol: "B" },
      { label: "Period:", placeholder: "Q1 2026", row: 2, labelCol: "F", valueCol: "G" },
      { label: "Territory:", placeholder: "Northeast", row: 3, labelCol: "A", valueCol: "B" },
      { label: "Manager:", placeholder: "John Smith", row: 3, labelCol: "F", valueCol: "G" },
    ],
    headerRow: 5,
    columns: [
      { header: "Lead #", col: "A", width: 8, alignment: "Center" },
      { header: "Company Name", col: "B", width: 20, alignment: "Left" },
      { header: "Contact Person", col: "C", width: 18, alignment: "Left" },
      { header: "Phone", col: "D", width: 14, alignment: "Center" },
      { header: "Email", col: "E", width: 22, alignment: "Left" },
      { header: "Lead Source", col: "F", width: 14, alignment: "Left" },
      { header: "Status", col: "G", width: 14, alignment: "Center", isAccent: true },
      { header: "Est. Value", col: "H", width: 14, alignment: "Right", isAccent: true },
      { header: "Probability", col: "I", width: 12, alignment: "Center" },
      { header: "Follow-Up Date", col: "J", width: 14, alignment: "Center" },
      { header: "Notes", col: "K", width: 20, alignment: "Left" },
    ],
    sampleData: [
      [1, "Acme Industries", "Robert Chen", "(555) 100-2001", "rchen@acme.com", "Referral", "Qualified", 45000, "75%", "03/20/2026", "Needs demo"],
      [2, "TechStart LLC", "Maria Lopez", "(555) 100-2002", "mlopez@techstart.com", "Website", "New", 12000, "25%", "03/18/2026", "Initial contact"],
      [3, "Global Retail", "James Park", "(555) 100-2003", "jpark@globalretail.com", "Trade Show", "Proposal", 78000, "60%", "03/22/2026", "Sent proposal 3/10"],
      [4, "Bright Health", "Susan Wu", "(555) 100-2004", "swu@brighthealth.com", "Cold Call", "Negotiation", 35000, "80%", "03/19/2026", "Pricing review"],
      [5, "DataFlow Inc.", "Kevin Rao", "(555) 100-2005", "krao@dataflow.com", "LinkedIn", "Qualified", 62000, "50%", "03/25/2026", "Budget approval pending"],
      [6, "Summit Group", "Lisa Grant", "(555) 100-2006", "lgrant@summit.com", "Referral", "Won", 28000, "100%", "—", "Closed 3/12"],
    ],
    totalRow: {
      row: 12,
      label: "PIPELINE TOTAL",
      labelCol: "A",
      values: { H: 260000 },
    },
    zones: [
      { type: "title", rows: 1 },
      { type: "meta", rows: [2, 3] },
      { type: "spacer", rows: 4 },
      { type: "column_header", rows: 5 },
      { type: "data", rows: 6 },
      { type: "data_alternate", rows: 7 },
      { type: "data", rows: 8 },
      { type: "data_alternate", rows: 9 },
      { type: "data", rows: 10 },
      { type: "data_alternate", rows: 11 },
      { type: "total", rows: 12 },
    ],
    columnSpan: "A:K",
    totalRows: 12,
  },
  sourceKind: "bundled",
};
