import type { TemplateDefinition } from "../types.js";

export const SALES_FORECAST_12M: TemplateDefinition = {
  id: "sales-forecast-12m",
  name: "12-Month Sales Forecast",
  category: "sales",
  description:
    "Project monthly sales revenue over a 12-month horizon with growth assumptions and quarterly subtotals.",
  design: {
    palette: {
      titleBg: "#2F5496",
      titleFg: "#FFFFFF",
      headerBg: "#D6E4F0",
      headerFg: "#000000",
      labelBg: "#D6E4F0",
      labelFg: "#000000",
      accentBg: "#2F5496",
      accentFg: "#FFFFFF",
      alternateBg: "#F2F2F2",
      totalBg: "#D6E4F0",
      totalFg: "#000000",
    },
    typography: {
      fontFamily: "Calibri",
      titleFontFamily: "Calibri",
      titleSize: 26,
      sectionHeaderSize: 14,
      headerSize: 11,
      bodySize: 11,
    },
    alternatingRows: true,
    titleBold: true,
    titleRowHeight: 40,
    defaultRowHeight: 20,
    headerRowHeight: 25,
  },
  structure: {
    title: "12-Month Sales Forecast",
    titleRow: 1,
    metaFields: [
      { label: "Company:", placeholder: "Acme Corp", row: 2, labelCol: "A", valueCol: "B" },
      { label: "Fiscal Year:", placeholder: "2026", row: 2, labelCol: "D", valueCol: "E" },
      { label: "Prepared By:", placeholder: "Sales Director", row: 3, labelCol: "A", valueCol: "B" },
      { label: "Date:", placeholder: "03/15/2026", row: 3, labelCol: "D", valueCol: "E" },
    ],
    headerRow: 5,
    columns: [
      { header: "Month", col: "A", width: 14, alignment: "Left" },
      { header: "Units Sold", col: "B", width: 12, alignment: "Right" },
      { header: "Avg Price", col: "C", width: 12, alignment: "Right" },
      { header: "Revenue", col: "D", width: 14, alignment: "Right", isAccent: true },
      { header: "Growth %", col: "E", width: 10, alignment: "Center" },
    ],
    sampleData: [
      ["January", 120, 85.00, 10200.00, "—"],
      ["February", 135, 85.00, 11475.00, "12.5%"],
      ["March", 150, 87.00, 13050.00, "13.7%"],
      ["April", 140, 87.00, 12180.00, "-6.7%"],
      ["May", 160, 88.00, 14080.00, "15.6%"],
      ["June", 175, 88.00, 15400.00, "9.4%"],
    ],
    totalRow: {
      row: 18,
      label: "ANNUAL TOTAL",
      labelCol: "A",
      values: { B: 1860, D: 163800.00 },
    },
    zones: [
      { type: "title", rows: 1 },
      { type: "meta", rows: [2, 3] },
      { type: "spacer", rows: 4 },
      { type: "column_header", rows: 5 },
      { type: "data", rows: 6 },
      { type: "data_alternate", rows: 7 },
      { type: "data", rows: 8 },
      { type: "data_alternate", rows: 9 },
      { type: "data", rows: 10 },
      { type: "data_alternate", rows: 11 },
      { type: "total", rows: 18 },
    ],
    columnSpan: "A:E",
    totalRows: 18,
  },
  sourceKind: "bundled",
};
