import type { TemplateDefinition } from "../types.js";

export const SALES_BALANCED_SCORECARD: TemplateDefinition = {
  id: "sales-balanced-scorecard",
  name: "Sales Balanced Scorecard",
  category: "sales",
  description:
    "Measure sales performance across financial, customer, process and growth perspectives with weighted scoring.",
  design: {
    palette: {
      titleBg: "#4472C4",
      titleFg: "#FFFFFF",
      headerBg: "#D6E4F0",
      headerFg: "#000000",
      labelBg: "#D6E4F0",
      labelFg: "#000000",
      accentBg: "#4472C4",
      accentFg: "#FFFFFF",
      alternateBg: "#F2F2F2",
      totalBg: "#D6E4F0",
      totalFg: "#000000",
    },
    typography: {
      fontFamily: "Calibri",
      titleFontFamily: "Calibri",
      titleSize: 26,
      sectionHeaderSize: 14,
      headerSize: 11,
      bodySize: 11,
    },
    alternatingRows: false,
    titleBold: true,
    titleRowHeight: 40,
    defaultRowHeight: 20,
    headerRowHeight: 25,
  },
  structure: {
    title: "Sales Balanced Scorecard",
    titleRow: 1,
    metaFields: [
      { label: "Company:", placeholder: "Acme Corp", row: 2, labelCol: "A", valueCol: "B" },
      { label: "Period:", placeholder: "Q1 2026", row: 2, labelCol: "E", valueCol: "F" },
      { label: "Prepared By:", placeholder: "Sales Manager", row: 3, labelCol: "A", valueCol: "B" },
      { label: "Date:", placeholder: "03/15/2026", row: 3, labelCol: "E", valueCol: "F" },
    ],
    headerRow: 5,
    columns: [
      { header: "Perspective", col: "A", width: 16, alignment: "Left" },
      { header: "Objective", col: "B", width: 22, alignment: "Left" },
      { header: "KPI", col: "C", width: 20, alignment: "Left" },
      { header: "Target", col: "D", width: 12, alignment: "Right" },
      { header: "Actual", col: "E", width: 12, alignment: "Right" },
      { header: "Score", col: "F", width: 10, alignment: "Center", isAccent: true },
      { header: "Weight", col: "G", width: 10, alignment: "Center" },
      { header: "Weighted Score", col: "H", width: 14, alignment: "Right", isAccent: true },
    ],
    sampleData: [
      ["Financial", "Revenue Growth", "Revenue vs Target", "$500K", "$475K", 95, "25%", 23.75],
      ["Financial", "Profit Margin", "Gross Margin %", "40%", "38%", 95, "15%", 14.25],
      ["Customer", "Satisfaction", "NPS Score", 80, 76, 95, "15%", 14.25],
      ["Customer", "Retention", "Renewal Rate", "90%", "88%", 98, "10%", 9.80],
      ["Process", "Pipeline", "Conversion Rate", "25%", "22%", 88, "15%", 13.20],
      ["Growth", "Training", "Certifications", 10, 8, 80, "20%", 16.00],
    ],
    totalRow: {
      row: 12,
      label: "OVERALL SCORE",
      labelCol: "A",
      values: { H: 91.25 },
    },
    zones: [
      { type: "title", rows: 1 },
      { type: "meta", rows: [2, 3] },
      { type: "spacer", rows: 4 },
      { type: "column_header", rows: 5 },
      { type: "data", rows: 6 },
      { type: "data", rows: 7 },
      { type: "data", rows: 8 },
      { type: "data", rows: 9 },
      { type: "data", rows: 10 },
      { type: "data", rows: 11 },
      { type: "total", rows: 12 },
    ],
    columnSpan: "A:H",
    totalRows: 12,
  },
  sourceKind: "bundled",
};
