import type { TemplateDefinition } from "../types.js";

export const WORK_PLANNER: TemplateDefinition = {
  id: "work-planner",
  name: "Work Planner Sheet",
  category: "planning",
  description:
    "Organize tasks and milestones with priorities, deadlines, owners, and progress tracking.",
  design: {
    palette: {
      titleBg: "#375623",
      titleFg: "#FFFFFF",
      headerBg: "#E2EFDA",
      headerFg: "#000000",
      labelBg: "#E2EFDA",
      labelFg: "#000000",
      accentBg: "#375623",
      accentFg: "#FFFFFF",
      alternateBg: "#F2F2F2",
      totalBg: "#E2EFDA",
      totalFg: "#000000",
    },
    typography: {
      fontFamily: "Calibri",
      titleFontFamily: "Calibri",
      titleSize: 26,
      sectionHeaderSize: 14,
      headerSize: 11,
      bodySize: 11,
    },
    alternatingRows: true,
    titleBold: true,
    titleRowHeight: 40,
    defaultRowHeight: 20,
    headerRowHeight: 25,
  },
  structure: {
    title: "Work Planner Sheet",
    titleRow: 1,
    metaFields: [
      { label: "Project:", placeholder: "Website Redesign", row: 2, labelCol: "A", valueCol: "B" },
      { label: "Start Date:", placeholder: "03/01/2026", row: 2, labelCol: "F", valueCol: "G" },
      { label: "Team Lead:", placeholder: "Jane Doe", row: 3, labelCol: "A", valueCol: "B" },
      { label: "Due Date:", placeholder: "06/30/2026", row: 3, labelCol: "F", valueCol: "G" },
    ],
    headerRow: 5,
    columns: [
      { header: "Task #", col: "A", width: 8, alignment: "Center" },
      { header: "Task Name", col: "B", width: 24, alignment: "Left" },
      { header: "Category", col: "C", width: 14, alignment: "Left" },
      { header: "Priority", col: "D", width: 10, alignment: "Center", isAccent: true },
      { header: "Owner", col: "E", width: 16, alignment: "Left" },
      { header: "Start Date", col: "F", width: 12, alignment: "Center" },
      { header: "Due Date", col: "G", width: 12, alignment: "Center" },
      { header: "Status", col: "H", width: 14, alignment: "Center", isAccent: true },
      { header: "% Complete", col: "I", width: 12, alignment: "Center" },
      { header: "Notes", col: "J", width: 20, alignment: "Left" },
    ],
    sampleData: [
      [1, "Gather requirements", "Planning", "High", "Alice Johnson", "03/01", "03/07", "Complete", "100%", "Stakeholder sign-off"],
      [2, "Create wireframes", "Design", "High", "Bob Smith", "03/08", "03/14", "Complete", "100%", "Approved by client"],
      [3, "Design mockups", "Design", "High", "Bob Smith", "03/15", "03/28", "In Progress", "65%", "Mobile views pending"],
      [4, "Set up CI/CD pipeline", "Development", "Medium", "Carol White", "03/10", "03/17", "Complete", "100%", "GitHub Actions"],
      [5, "Frontend development", "Development", "High", "Dave Brown", "03/22", "04/18", "In Progress", "30%", "React + Tailwind"],
      [6, "API integration", "Development", "Medium", "Carol White", "04/01", "04/15", "Not Started", "0%", "REST endpoints"],
    ],
    zones: [
      { type: "title", rows: 1 },
      { type: "meta", rows: [2, 3] },
      { type: "spacer", rows: 4 },
      { type: "column_header", rows: 5 },
      { type: "data", rows: 6 },
      { type: "data_alternate", rows: 7 },
      { type: "data", rows: 8 },
      { type: "data_alternate", rows: 9 },
      { type: "data", rows: 10 },
      { type: "data_alternate", rows: 11 },
    ],
    columnSpan: "A:J",
    totalRows: 11,
  },
  sourceKind: "bundled",
};
